project:
  type: book

book:
  chapters:
    - cover.qmd
    - index.qmd
    - summary.qmd
    - Introduccion.qmd
    - Metodologia.qmd
    - Resultados.qmd
    - Referencias.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
    geometry:
       - top=30mm
       - bottom=30mm
       - left=30mm
       - right=30mm
       - heightrounded
    includes:
      in_header: header.tex

    #reference-location: margin
    #citation-location: margin
    #fig-cap-location: bottom
    #classoption: [sfsidenotes]
    
    number-sections: true
    lang: es
    colorlinks: true
    linkcolor: RoyalBlue
    filecolor: Blue
    citecolor:  Goldenrod #YellowOrange
    urlcolor: RoyalBlue #ForestGreen
    toccolor: Black # MidnightBlue, RoyalBlue
    tblcolor: Black
    mainfont: Arial  #Arial Narrow or Roboto Condensed, verdana
    fontsize: 12pt
    fig_caption:  true
    toc: true
    lof: true
    lot: true
    toc-depth: 3
    toc-Title: "Tabla de contenidos"
    lof-Title: "Lista de figuras"
    lot-Title: "Lista de tabla"
    biblio-style: plos-one.csl
#    csl: plos-one.csl
    biblio-title: "bibliografia"
    keep-tex: true 
    keep-md: true
    link-citations: true
    
    crossref:
      fig-prefix: "Figura"
      tbl-prefix: "Tabla"
    page-layout: full
    header-includes:
      #- \usepackage[spanish]{babel}
      - \usepackage[dvipsnames]{xcolor}
      - \usepackage[T1]{fontenc}
      
    highlight-style: espresso #github 
    
  epub:
    cover-image: cover.png
execute:
  freeze: auto



